UPDATE JUNIOR_CARD
SET PLAYER_ID = 1
WHERE ID = 1;
UPDATE JUNIOR_CARD
SET PLAYER_ID = 1
WHERE ID = 5;
UPDATE JUNIOR_CARD
SET PLAYER_ID = 1
WHERE ID = 7;

UPDATE BUG_CARD
SET BUG_ID = 1
WHERE ID = 1;
UPDATE BUG_CARD
SET BUG_ID = 1
WHERE ID = 5;
UPDATE BUG_CARD
SET BUG_ID = 1
WHERE ID = 7;