UPDATE JUNIOR_CARD
SET PLAYER_ID = 1
WHERE ID = 1;
UPDATE JUNIOR_CARD
SET PLAYER_ID = 1
WHERE ID = 5;
UPDATE JUNIOR_CARD
SET PLAYER_ID = 1
WHERE ID = 7;

INSERT INTO BUG(id, life, mana)
VALUES (1, 20, 20);

UPDATE BUG_CARD
SET IS_IN_USE = TRUE
WHERE ID = 1;
UPDATE BUG_CARD
SET IS_IN_USE = TRUE
WHERE ID = 5;
UPDATE BUG_CARD
SET IS_IN_USE = TRUE
WHERE ID = 7;